#ifndef PROTOMOL_PACKAGE_H
#define PROTOMOL_PACKAGE_H

/************************************************************
 * NOTE: This is an autogenerated file.  Please do not edit *
 *       directly or check in to revision control.          *
 ************************************************************/

#define PACKAGE_VERSION "3.3"
#define PACKAGE_BUGREPORT \
  "protomol@cse.nd.edu, joseph@cauldrondevelopment.com"
#define PACKAGE_HOMEPAGE "http://protomol.sourceforge.net/"
#define PACKAGE_CITE \
  "T. Matthey, T. Cickovski, S. S. Hampton, A. Ko, Q. Ma,\n"\
  "M. Nyerges, T. Raeder, T. Slabach, and J. A. Izaguirre.\n"\
  "ProtoMol: An object-oriented framework for prototyping novel algorithms\n"\
  "for molecular dynamics.\n"\
  "ACM Trans. Math. Softw., 30(3):237 265, 2004."
#define PACKAGE_REVISION "2024"
#define PACKAGE_SOURCE_REPO \
  "https://protomol.svn.sourceforge.net/svnroot/protomol/trunk/protomol"
#define PACKAGE_COMPILER "g++"
#define PACKAGE_COMPILER_VERSION "4.6.1"
#define PACKAGE_COMPILER_FLAGS "-std=gnu++98 -DDEBUG -D_REENTRANT -DHAVE_LAPACK"
#define PACKAGE_COMPILER_LIBS "lapack blas pthread"
#define PACKAGE_BUILT_BY "kuangchen"
#define PACKAGE_PLATFORM "posix"

#endif // PROTOMOL_PACKAGE_H
